spring:
    application:
        name : user-service
    datasource:
        url: ${USERS_DB_URL:jdbc:postgresql://localhost:5432/users_db}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
    jpa:
        hibernate.ddl-auto: update
        show-sql: true

server:
  port: 8082

service:
  urls:
    api-gateway:  ${API_GATEWAY_URL:http://localhost:8080}
    auth-service: ${AUTH_SERVICE_URL:http://localhost:8081}
    user-service: ${USER_SERVICE_URL:http://localhost:8082}
    restaurant-service: ${RESTAURANT_SERVICE_URL:http://localhost:8083}
    media-service: ${MEDIA_SERVICE_URL:http://localhost:8084}
    reservation-service: ${RESERVATION_SERVICE_URL:http://localhost:8085}
    menu-item-service: ${MENU_ITEM_SERVICE_URL:http://localhost:8087}
